const { signPayload, verifySignature } = require('../../src/utils/hmac');

describe('signPayload', () => {
  const secret = 'whsec_test_secret';
  const rawBody = '{"eventType":"user.created","payload":{"id":1}}';
  const timestamp = 1700000000000;

  it('produces a deterministic signature for fixed inputs', () => {
    // Regression guard on the exact signing scheme: HMAC-SHA256 of
    // "${timestamp}.${rawBody}". If this value ever changes, the signing
    // algorithm changed and the README's subscriber guide needs updating.
    const signature = signPayload(secret, rawBody, timestamp);
    expect(signature).toBe('f7b3845bf8a0b2fac1565e721f1ee644d6c31eb5aed1d7a9a5b583da4dceda5d');
  });

  it('is deterministic: same inputs always produce the same signature', () => {
    const first = signPayload(secret, rawBody, timestamp);
    const second = signPayload(secret, rawBody, timestamp);
    expect(first).toBe(second);
  });

  it('produces different signatures for different bodies', () => {
    const a = signPayload(secret, rawBody, timestamp);
    const b = signPayload(secret, '{"different":"body"}', timestamp);
    expect(a).not.toBe(b);
  });

  it('produces different signatures for different secrets', () => {
    const a = signPayload('secret-a', rawBody, timestamp);
    const b = signPayload('secret-b', rawBody, timestamp);
    expect(a).not.toBe(b);
  });

  it('produces different signatures for different timestamps', () => {
    const a = signPayload(secret, rawBody, timestamp);
    const b = signPayload(secret, rawBody, timestamp + 1);
    expect(a).not.toBe(b);
  });
});

describe('verifySignature', () => {
  const secret = 'whsec_test_secret';
  const rawBody = '{"eventType":"user.created","payload":{"id":1}}';
  const timestamp = 1700000000000;

  it('accepts a signature generated by signPayload with matching inputs', () => {
    const signature = signPayload(secret, rawBody, timestamp);
    expect(verifySignature(secret, rawBody, timestamp, signature)).toBe(true);
  });

  it('rejects a signature computed with the wrong secret', () => {
    const signature = signPayload('wrong-secret', rawBody, timestamp);
    expect(verifySignature(secret, rawBody, timestamp, signature)).toBe(false);
  });

  it('rejects a signature checked against a tampered body', () => {
    const signature = signPayload(secret, rawBody, timestamp);
    expect(verifySignature(secret, '{"eventType":"tampered"}', timestamp, signature)).toBe(false);
  });

  it('rejects a signature checked against a tampered timestamp', () => {
    const signature = signPayload(secret, rawBody, timestamp);
    expect(verifySignature(secret, rawBody, timestamp + 5000, signature)).toBe(false);
  });

  it('rejects a malformed (non-hex) signature without throwing', () => {
    expect(() => verifySignature(secret, rawBody, timestamp, 'not-a-hex-signature')).not.toThrow();
    expect(verifySignature(secret, rawBody, timestamp, 'not-a-hex-signature')).toBe(false);
  });

  it('rejects a truncated signature without throwing', () => {
    const signature = signPayload(secret, rawBody, timestamp).slice(0, 10);
    expect(() => verifySignature(secret, rawBody, timestamp, signature)).not.toThrow();
    expect(verifySignature(secret, rawBody, timestamp, signature)).toBe(false);
  });

  it('rejects an empty or missing signature', () => {
    expect(verifySignature(secret, rawBody, timestamp, '')).toBe(false);
    expect(verifySignature(secret, rawBody, timestamp, undefined)).toBe(false);
  });
});
